// 主表格数据
export const tableData = [
  {
    xinghao: 'H-1071',
    tupian: 'H-1071',
    mingcheng: '上包边',
    guige: '1416',
    shuliang: '2',
    beizhu: '打磨喷漆',
    _mergeXinghao: 2,
    _mergeTupian: 2,
    _mergeMingcheng: 2,
  },
  {
    xinghao: 'H-1071',
    tupian: 'H-1071',
    mingcheng: '上包边',
    guige: '516',
    shuliang: '2',
    beizhu: '打磨喷漆',
    _mergeXinghao: 0,
    _mergeTupian: 0,
    _mergeMingcheng: 0,
  },

  {
    xinghao: 'H-1072',
    tupian: 'H-1072',
    mingcheng: '下包边',
    guige: '1416',
    shuliang: '2',
    beizhu: '',
    _mergeXinghao: 2,
    _mergeTupian: 2,
    _mergeMingcheng: 2,
  },
  {
    xinghao: 'H-1072',
    tupian: 'H-1072',
    mingcheng: '下包边',
    guige: '516',
    shuliang: '2',
    beizhu: '',
    _mergeXinghao: 0,
    _mergeTupian: 0,
    _mergeMingcheng: 0,
  },

  {
    xinghao: 'H-1073',
    tupian: 'H-1073',
    mingcheng: '立柱',
    guige: '897',
    shuliang: '4',
    beizhu: '',
    _mergeXinghao: 1,
    _mergeTupian: 1,
    _mergeMingcheng: 1,
  },

  {
    xinghao: 'H-1074',
    tupian: 'H-1074',
    mingcheng: '前后横梁',
    guige: '1420',
    shuliang: '4',
    beizhu: '',
    _mergeXinghao: 1,
    _mergeTupian: 1,
    _mergeMingcheng: 1,
  },

  {
    xinghao: 'H-1075',
    tupian: 'H-1075',
    mingcheng: '侧横梁',
    guige: '460',
    shuliang: '4',
    beizhu: '',
    _mergeXinghao: 1,
    _mergeTupian: 1,
    _mergeMingcheng: 1,
  },

  {
    xinghao: 'H-1076',
    tupian: 'H-1076',
    mingcheng: '中柱',
    guige: '810',
    shuliang: '',
    beizhu: '冲孔',
    _mergeXinghao: 1,
    _mergeTupian: 1,
    _mergeMingcheng: 1,
  },

  {
    xinghao: 'H-1005',
    tupian: 'H-1005',
    mingcheng: '拉筋',
    guige: '498',
    shuliang: '',
    beizhu: '',
    _mergeXinghao: 1,
    _mergeTupian: 1,
    _mergeMingcheng: 1,
  },

  {
    xinghao: 'H-1005',
    tupian: 'H-1005',
    mingcheng: '横拉',
    guige: '460',
    shuliang: '1',
    beizhu: '',
    _mergeXinghao: 1,
    _mergeTupian: 1,
    _mergeMingcheng: 1,
  },

  {
    xinghao: 'H-1077',
    tupian: 'H-1077',
    mingcheng: '门料',
    guige: '470.7',
    shuliang: '',
    beizhu: '45度切',
    _mergeXinghao: 4,
    _mergeTupian: 4,
    _mergeMingcheng: 4,
  },
  {
    xinghao: 'H-1077',
    tupian: 'H-1077',
    mingcheng: '门料',
    guige: '875',
    shuliang: '',
    beizhu: '一半冲孔',
    _mergeXinghao: 0,
    _mergeTupian: 0,
    _mergeMingcheng: 0,
  },
  {
    xinghao: 'H-1077',
    tupian: 'H-1077',
    mingcheng: '侧板',
    guige: '515',
    shuliang: '4',
    beizhu: '',
    _mergeXinghao: 0,
    _mergeTupian: 0,
    _mergeMingcheng: 0,
  },
  {
    xinghao: 'H-1077',
    tupian: 'H-1077',
    mingcheng: '侧板',
    guige: '899',
    shuliang: '4',
    beizhu: '',
    _mergeXinghao: 0,
    _mergeTupian: 0,
    _mergeMingcheng: 0,
  },
]
